# Generated by Django 5.0.1 on 2024-01-24 14:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('tel', models.CharField(max_length=10, verbose_name='Tel')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='CompletedConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_code', models.CharField(max_length=20)),
                ('topic_title', models.CharField(max_length=255)),
                ('submission_date', models.DateTimeField()),
                ('details', models.TextField()),
                ('document', models.ImageField(blank=True, null=True, upload_to='completed_consultations/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_code', models.CharField(choices=[('ADM01', 'ADM01'), ('ADM02', 'ADM02'), ('ADM03', 'ADM03'), ('REG04', 'REG04'), ('REG05', 'REG05'), ('UP01', 'UP01'), ('UP02', 'UP02'), ('UP03', 'UP03'), ('UP03.1', 'UP03.1'), ('UP05', 'UP05'), ('UP06', 'UP06'), ('UP07', 'UP07'), ('UP08', 'UP08'), ('UP09', 'UP09'), ('UP10', 'UP10'), ('UP11', 'UP11'), ('UP12', 'UP12'), ('UP13', 'UP13'), ('UP14', 'UP14'), ('UP17', 'UP17'), ('UP18', 'UP18'), ('UP20.1', 'UP20.1'), ('UP24', 'UP24'), ('UP25', 'UP25'), ('UP29', 'UP29'), ('UP30', 'UP30')], max_length=10)),
                ('topic_title', models.CharField(choices=[('ADM01', 'สมัครโครงการรับนิสิตกลับเข้าศึกษาในมหาวิทยาลัยพะเยา (รีรหัส)'), ('ADM02', 'คำร้องขอส่งใบรับรองแพทย์'), ('ADM03', 'คำร้องส่งข้อมูลผลการสอบ TPAT5 ความถนัดครุศาสตร์-ศึกษาศาสตร์'), ('REG04', 'คำร้องขอรับผลการเรียนรายวิชาในหมวดวิชาศึกษาทั่วไป'), ('REG05', 'คำร้องขอพัฒนาผลการเรียนรายวิชาในหมวดวิชาศึกษาทั่วไป'), ('UP01', 'คำร้องทั่วไป'), ('UP02', 'คำร้องขอใบรับรอง'), ('UP03', 'คำร้องขอใบรายงานผลการศึกษา (Transcript)'), ('UP03.1', 'คำร้องขอใบรายงานผลการศึกษา (Digital Transcript)'), ('UP05', 'คำร้องขอเพิ่มรายวิชาหลังกำหนด'), ('UP06', 'คำร้องขอลงทะเบียนเรียนมากกว่า/น้อยกว่าเกณฑ์'), ('UP07', 'คำร้องขออนุมัติเทียบรายวิชา'), ('UP08', 'คำร้องขอถอนรายวิชา โดยได้รับอักษร W'), ('UP09', 'คำร้องขอเทียบโอนรายวิชา'), ('UP10', 'คำร้องขอย้ายคณะ/หลักสูตร/แผนการเรียน'), ('UP11', 'คำร้องขอเปลี่ยนชื่อ ชื่อสกุล ยศ และอื่นๆ'), ('UP12', 'คำร้องขอลาพักการศึกษา'), ('UP13', 'คำร้องขอลาออกจากการศึกษา'), ('UP14', 'คำร้องขอลงทะเบียนเรียนพร้อมฝึกงาน/การศึกษาอิสระ/วิทยานิพนธ์'), ('UP17', 'คำร้องขอผ่อนผันการชำระค่าลงทะเบียนเรียน'), ('UP18', 'คำร้องขอผ่อนผันการชำระค่าลงทะเบียนเรียน'), ('UP20.1', 'คำร้องยื่นความประสงค์ขอลงทะเบียนเรียนรายวิชา'), ('UP24', 'คำร้องขอสำเร็จการศึกษา'), ('UP29', 'คำร้องขอยื่นสำเร็จการศึกษาล่าช้ากว่ากำหนด'), ('UP30', 'คำร้องขอถอนรายวิชาศึกษาทั่วไป (GE-Online)')], max_length=10)),
                ('submission_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('received_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('details', models.TextField()),
                ('document', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('status', models.CharField(choices=[('Pending', 'รอดำเนินการ'), ('Processing', 'กำลังดำเนินการ'), ('Completed', 'เสร็จสิ้น'), ('Appointment', 'การนัดหมาย')], default='pending', max_length=50)),
                ('full_name', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
