# Generated by Django 5.0.1 on 2024-02-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.CharField(default=1, max_length=100, verbose_name='Major'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CompletedConsultation',
        ),
    ]
