# Generated by Django 5.0.1 on 2024-02-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_major_delete_completedconsultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='major',
            field=models.CharField(choices=[('SE', 'สาขาวิชาวิศวกรรมซอฟต์แวร์'), ('CS', 'สาขาวิชาวิทยาการคอมพิวเตอร์'), ('CPE', 'สาขาวิชาวิศวกรรมคอมพิวเตอร์'), ('IT', 'สาขาวิชาเทคโนโลยีสารสนเทศ'), ('BS', 'สาขาวิชาภูมิสารสนเทศศาสตร์'), ('BBA', 'สาขาวิชาธุรกิจดิจิทัล'), ('CG', 'สาขาวิชาคอมพิวเตอร์กราฟิกและมัลติมีเดีย'), ('BSC', 'สาขาวิชาวิทยาการข้อมูลและการประยุกต์'), ('ICTE', 'สาขาวิชาเทคโนโลยีสารสนเทศและสาขาวิชาภาษาอังกฤษ')], max_length=100, verbose_name='Major'),
        ),
    ]
