# Generated by Django 5.0.1 on 2024-01-13 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(choices=[('faculty1', 'Faculty 1')], max_length=255)),
                ('major', models.CharField(choices=[('major1', 'Major 1')], max_length=255)),
                ('topic_code', models.CharField(choices=[('code1', 'Code 1')], max_length=10)),
                ('topic_title', models.CharField(choices=[('title1', 'Title 1')], max_length=10)),
                ('submission_date', models.DateField()),
                ('received_date', models.DateField(blank=True, null=True)),
                ('details', models.TextField()),
                ('document', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('status', models.CharField(choices=[('Pending', 'รอดำเนินการ'), ('Processing', 'กำลังดำเนินการ'), ('Completed', 'เสร็จสิ้น'), ('Appointment', 'การนัดหมาย')], default='pending', max_length=50)),
                ('full_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
