# Generated by Django 5.0.1 on 2024-02-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_consultationrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='major',
            field=models.CharField(blank=True, choices=[('SE', 'สาขาวิชาวิศวกรรมซอฟต์แวร์'), ('CS', 'สาขาวิชาวิทยาการคอมพิวเตอร์'), ('CPE', 'สาขาวิชาวิศวกรรมคอมพิวเตอร์'), ('IT', 'สาขาวิชาเทคโนโลยีสารสนเทศ'), ('BS', 'สาขาวิชาภูมิสารสนเทศศาสตร์'), ('BBA', 'สาขาวิชาธุรกิจดิจิทัล'), ('CG', 'สาขาวิชาคอมพิวเตอร์กราฟิกและมัลติมีเดีย'), ('BSC', 'สาขาวิชาวิทยาการข้อมูลและการประยุกต์'), ('ICTE', 'สาขาวิชาเทคโนโลยีสารสนเทศและสาขาวิชาภาษาอังกฤษ')], max_length=100),
        ),
    ]
