# Generated by Django 5.0.1 on 2024-01-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_options_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='faculty',
            field=models.CharField(choices=[('faculty1', 'คณะเทคโนโลยีสารสนเทศ')], max_length=255),
        ),
    ]
