# Generated by Django 5.0.1 on 2024-02-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultation_request_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
