# Generated by Django 5.0.1 on 2024-01-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_consultationrequest_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='topic_code',
            field=models.CharField(choices=[('ADM01', 'ADM01'), ('ADM02', 'ADM02'), ('ADM03', 'ADM03'), ('REG04', 'REG04'), ('REG05', 'REG05'), ('UP01', 'UP01'), ('UP02', 'UP02'), ('UP03', 'UP03'), ('UP03.1', 'UP03.1'), ('UP05', 'UP05'), ('UP06', 'UP06'), ('UP07', 'UP07'), ('UP08', 'UP08'), ('UP09', 'UP09'), ('UP10', 'UP10'), ('UP11', 'UP11'), ('UP12', 'UP12'), ('UP13', 'UP13'), ('UP14', 'UP14'), ('UP17', 'UP17'), ('UP18', 'UP18'), ('UP20.1', 'UP20.1'), ('UP24', 'UP24'), ('UP25', 'UP25'), ('UP29', 'UP29'), ('UP30', 'UP30')], max_length=10),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='topic_title',
            field=models.CharField(choices=[('ADM01', 'สมัครโครงการรับนิสิตกลับเข้าศึกษาในมหาวิทยาลัยพะเยา (รีรหัส)'), ('ADM02', 'คำร้องขอส่งใบรับรองแพทย์'), ('ADM03', 'คำร้องส่งข้อมูลผลการสอบ TPAT5 ความถนัดครุศาสตร์-ศึกษาศาสตร์'), ('REG04', 'คำร้องขอรับผลการเรียนรายวิชาในหมวดวิชาศึกษาทั่วไป'), ('REG05', 'คำร้องขอพัฒนาผลการเรียนรายวิชาในหมวดวิชาศึกษาทั่วไป'), ('UP01', 'คำร้องทั่วไป'), ('UP02', 'คำร้องขอใบรับรอง'), ('UP03', 'คำร้องขอใบรายงานผลการศึกษา (Transcript)'), ('UP03.1', 'คำร้องขอใบรายงานผลการศึกษา (Digital Transcript)'), ('UP05', 'คำร้องขอเพิ่มรายวิชาหลังกำหนด'), ('UP06', 'คำร้องขอลงทะเบียนเรียนมากกว่า/น้อยกว่าเกณฑ์'), ('UP07', 'คำร้องขออนุมัติเทียบรายวิชา'), ('UP08', 'คำร้องขอถอนรายวิชา โดยได้รับอักษร W'), ('UP09', 'คำร้องขอเทียบโอนรายวิชา'), ('UP10', 'คำร้องขอย้ายคณะ/หลักสูตร/แผนการเรียน'), ('UP11', 'คำร้องขอเปลี่ยนชื่อ ชื่อสกุล ยศ และอื่นๆ'), ('UP12', 'คำร้องขอลาพักการศึกษา'), ('UP13', 'คำร้องขอลาออกจากการศึกษา'), ('UP14', 'คำร้องขอลงทะเบียนเรียนพร้อมฝึกงาน/การศึกษาอิสระ/วิทยานิพนธ์'), ('UP17', 'คำร้องขอผ่อนผันการชำระค่าลงทะเบียนเรียน'), ('UP18', 'คำร้องขอผ่อนผันการชำระค่าลงทะเบียนเรียน'), ('UP20.1', 'คำร้องยื่นความประสงค์ขอลงทะเบียนเรียนรายวิชา'), ('UP24', 'คำร้องขอสำเร็จการศึกษา'), ('UP29', 'คำร้องขอยื่นสำเร็จการศึกษาล่าช้ากว่ากำหนด'), ('UP30', 'คำร้องขอถอนรายวิชาศึกษาทั่วไป (GE-Online)')], max_length=10),
        ),
    ]
