# Generated by Django 5.0.1 on 2024-02-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_appointment_consultation_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
