# Generated by Django 5.0.1 on 2024-01-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationrequest',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='consultationrequest',
            name='major',
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
